CREATE TABLE [dbo].[USER_SAVED_SETTINGS]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [UserID] INT NOT NULL, 
    [ObjectName] NVARCHAR(50) NOT NULL, 
    [ObjectValue] NVARCHAR(50) NOT NULL, 
    [DateUpdated] DATETIME NULL, 
    CONSTRAINT [FK_UserSavedSettings_ToUsers] FOREIGN KEY (UserId) REFERENCES Users(Id)
	
)
