//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Algorithms
    {
        public Algorithms()
        {
            this.TestResults = new HashSet<TestResults>();
            this.TestRuns = new HashSet<TestRuns>();
        }
    
        public int Id { get; set; }
        public int CreatorId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfCreation { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<TestResults> TestResults { get; set; }
        public virtual ICollection<TestRuns> TestRuns { get; set; }
    }
}
