//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALGORITHMS
    {
        public ALGORITHMS()
        {
            this.TEST_RUN_RESULTS = new HashSet<TEST_RUN_RESULTS>();
            this.TEST_RUNS = new HashSet<TEST_RUNS>();
        }
    
        public int Id { get; set; }
        public int CreatorId { get; set; }
        public string Description { get; set; }
        public string SourceCode { get; set; }
        public string RunsCount { get; set; }
        public int AlgoritmType { get; set; }
    
        public virtual ALGORITHM_TYPES ALGORITHM_TYPES { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual ICollection<TEST_RUN_RESULTS> TEST_RUN_RESULTS { get; set; }
        public virtual ICollection<TEST_RUNS> TEST_RUNS { get; set; }
    }
}
