//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public int Id { get; set; }
        public int AlgorithmId { get; set; }
        public Nullable<int> TP { get; set; }
        public Nullable<int> FN { get; set; }
        public Nullable<int> TN { get; set; }
        public Nullable<int> FP { get; set; }
        public string Others { get; set; }
        public Nullable<int> TestRuns { get; set; }
    
        public virtual Algorithms Algorithms { get; set; }
        public virtual TestRuns TestRuns1 { get; set; }
    }
}
