//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_RUNS
    {
        public int Id { get; set; }
        public int AlgorithmId { get; set; }
        public int TestSetId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateOfRun { get; set; }
        public string RunComments { get; set; }
    
        public virtual ALGORITHMS ALGORITHMS { get; set; }
        public virtual TEST_DATA_SETS TEST_DATA_SETS { get; set; }
        public virtual TEST_RUN_RESULTS TEST_RUN_RESULTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
