//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        public int Id { get; set; }
        public int AlgorithmId { get; set; }
        public string TP { get; set; }
        public string FN { get; set; }
        public string TN { get; set; }
        public string FP { get; set; }
        public string RocCoordinatesSensiv { get; set; }
        public int TestRunId { get; set; }
        public string CorrectRate { get; set; }
        public string OtherInfo { get; set; }
        public string RocCoordinatesSpecif { get; set; }
    
        public virtual Algorithms Algorithms { get; set; }
        public virtual TestRuns TestRuns { get; set; }
    }
}
