//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGIN_ROLES
    {
        public USER_LOGIN_ROLES()
        {
            this.USERS = new HashSet<USERS>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
