//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Algorithms = new HashSet<Algorithms>();
            this.TestRuns = new HashSet<TestRuns>();
            this.TestSets = new HashSet<TestSets>();
            this.UserSavedSettings = new HashSet<UserSavedSettings>();
        }
    
        public int Id { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Algorithms> Algorithms { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<TestRuns> TestRuns { get; set; }
        public virtual ICollection<TestSets> TestSets { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserSavedSettings> UserSavedSettings { get; set; }
    }
}
