//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DETAILS
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string User_full_name { get; set; }
        public string Company { get; set; }
        public string Other { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
