//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SAVED_SETTINGS
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectValue { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
